services:
  - type: web
    name: face-recognition-attendance
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y python3-dev build-essential cmake libopenblas-dev liblapack-dev libx11-dev libgtk-3-dev && \
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: EMAIL_PASSWORD
        sync: false
